version: '3'

services:
  postgresql:
    image: postgres
    container_name: foodAPP
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=foodAPP
      - POSTGRES_PASSWORD=foodAPP
      - POSTGRES_DATABASE=foodAPP
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-foodAPP
    ports:
      - '6379:6379'
